feat: Added version-maestro script

diff --git a/src/utils/get-latest-changes b/src/utils/get-latest-changes
--- a/src/utils/get-latest-changes
+++ b/src/utils/get-latest-changes
@@ -2,18 +2,49 @@
 
 #get-latest-changes
 #by Julian Sangillo
-#Gets a newline separated list of the commit messages from HEAD up to the latest version.
+#Gets a newline separated, markdown formatted list of the commit messages from HEAD down to the latest version.
 
- LATEST_VERSION="$1";
+showHelp() {
+	echo "Usage: get-latest-changes [options...] [args...]";
+	echo "Gets a newline separated, markdown formatted list of the commit messages from";
+	echo "HEAD down to the latest version. If no version is specified, it will get the changes HEAD";
+	echo "down to the initial commit.";
+	echo "	";
+	echo "Options: ";
+	echo "	-v	Enter a released version and pull the latest changes from HEAD down";
+	echo "		to that version. The latest-version must not be empty and must be a";
+	echo "		period separated string of numbers and may have one release tag of";
+	echo "		letters appended to the end";
+	echo "		Usage: get-latest-changes -v <latest-version>";
+} >&2
+
+while getopts ":v:" opt; do
+	case "${opt}" in
+		v) 
+			LATEST_VERSION=$OPTARG
+			
+			if ! [[ "$LATEST_VERSION" =~ ^[0-9]+(\.[0-9]+)*(\.[A-Za-z]+)?$ ]]; then
+				log "Could not get latest changes! The version '$LATEST_VERSION' is invalid.";
+				echo "	" >&2;
+				showHelp;
+				exit 16
+			fi
+			;;
+		*)
+			log "Could not get latest changes! Unknown option '-${opt}'";
+			echo "	" >&2;
+			showHelp;
+			exit 1
+			;;
+	esac
+done
+shift $((OPTIND-1));
  
- if [ "$#" -ne 1 ]; then
+ if [ "$#" -ne 0 ]; then
 	log "Illegal number of arguments.";
+	echo "	" >&2;
+	showHelp;
 	exit 1
-fi
- 
- if ! [[ "$LATEST_VERSION" =~ ^[0-9]+(\.[0-9]+)*(\.[A-Za-z]+)?$ ]]; then
-	log "Could not get latest changes! The version '$LATEST_VERSION' is invalid.";
-	exit 16
 fi
 
 CHANGE_TYPES=('feat' 'fix' 'docs' 'style' 'refactor' 'perf' 'test' 'chore' 'build' 'patch' 'BREAKING CHANGE');
@@ -30,19 +61,29 @@ getChangeType() {
 getLatestChanges() {
 	log "Getting latest changes ...";
 
-	local history="$(git rev-list --ancestry-path HEAD ^v$LATEST_VERSION)";
+	if [ ! -z "$LATEST_VERSION" ]; then
+		local history="$(git rev-list --ancestry-path HEAD ^v$LATEST_VERSION)";
+	else
+		local history="$(git rev-list --all | head -n -1)";
+	fi
 	
+	if [ -z "$history" ]; then
+		log "No new history. Skipping";
+		return;
+	fi
+
 	local changes=();
 	while read -r commit; do
 		local date="$(git show -s --format=%ad --date=short $commit)";
-		local author="$(git show -s --format="%an [%ae]" $commit)";
+		local author_name="$(git show -s --format="%an" $commit)";
+		local author_email="$(git show -s --format="%ae" $commit)";
 		local message="$(git show -s --format=%s $commit | sed 's/^\([A-Z]\+'-'[0-9]\+\)\?//g' | sed 's/\(#major\|#minor\)\?//g' | sed 's/  / /g' | sed -e 's/^ *//' -e 's/ *$//')";
 		
 		local change_type=$(getChangeType $commit);
 
 		if [[ " ${CHANGE_TYPES[@]} " == *" $change_type "* ]]; then
-			log "$date $message | $author";
-			local changes+=("- **$date** $message | ***$author***");
+			log "$date $message | $author_name <$author_email>";
+			local changes+=("+ **$date** $message | ***$author_name*** *<[$author_email](mailto:$author_email)>*");
 		fi
 	done <<< "$history"
 	
diff --git a/src/utils/push-to-changelog b/src/utils/push-to-changelog
--- a/src/utils/push-to-changelog
+++ b/src/utils/push-to-changelog
@@ -1,42 +1,42 @@
 #! /bin/bash
 
-#push-to-changelog
+#push-to-CHANGELOG
 #by Julian Sangillo
-#Append the latest changes to the top of the current changelog (based on major revision) and sectioned of by full version.
+#Append the latest changes to the top of the current CHANGELOG (based on major revision) and sectioned of by full version.
 
 LATEST_CHANGES="$1";
 MAJOR_REVISION="$2";
 FULL_VERSION="$3";
 REVISION_TYPE="$4";
+CHANGELOG="$5";
 
-if [ "$#" -ne 4 ]; then
+if [ "$#" -ne 5 ]; then
 	log "Illegal number of arguments.";
 	exit 1
 fi
 
 if ! [[ "$FULL_VERSION" =~ ^[0-9]+(\.[0-9]+)*$ ]]; then
-	log "Could not push to changelog! The version '$FULL_VERSION' is invalid.";
+	log "Could not push to CHANGELOG! The version '$FULL_VERSION' is invalid.";
 	exit 16
 fi
 
 if [[ " major minor build patch " != *" ${REVISION_TYPE,,} "* ]]; then
-	log "Could not push to changelog! The revision type must be one of the following: major, minor, build, or patch.";
+	log "Could not push to CHANGELOG! The revision type must be one of the following: major, minor, build, or patch.";
 	exit 32
 fi
 
 pushToChangelog() {
 	log "Pushing to CHANGELOG ...";
 	
-	local changelog="./CHANGELOG.md";
-	local temp="/tmp/changelog.tmp";
+	local temp="/tmp/CHANGELOG.tmp";
 	
 	log "Major Revision: $MAJOR_REVISION";
 	log "Full Version: $FULL_VERSION";
 	log "Revision Type: $REVISION_TYPE";
-	log "CHANGELOG File: $changelog";
-	log "Total Changes: $(echo $LATEST_CHANGES | wc -l)";
+	log "CHANGELOG File: $CHANGELOG";
+	log "Total Changes: $(echo "$LATEST_CHANGES" | awk NF | wc -l)";
 	
-	if [ -z $LATEST_CHANGES ]; then
+	if [ -z "$LATEST_CHANGES" ]; then
 		log "No changes to push. Skipping";
 		return;
 	fi
@@ -44,20 +44,21 @@ pushToChangelog() {
 	log "Logging changes";
 	
 	echo "# CHANGELOG<br>$MAJOR_REVISION" > $temp;
+	echo "[//]: # (V:$FULL_VERSION T:${REVISION_TYPE,,})" >> $temp;
 	echo "### $FULL_VERSION" >> $temp;
 	echo "$LATEST_CHANGES" >> $temp;
 	
 	log "Changes logged";
 	
-	if [ "${REVISION_TYPE,,}" != "major" ] && [ -f $changelog ]; then
-		tail -n +2 $changelog >> $temp;
+	if [ "${REVISION_TYPE,,}" != "major" ] && [ -f $CHANGELOG ]; then
+		tail -n +2 $CHANGELOG >> $temp;
 	fi
 	
-	mv -f $temp $changelog;
+	mv -f $temp $CHANGELOG;
 	
-	commit $changelog "${REVISION_TYPE^^} $FULL_VERSION Update CHANGELOG.md" || exit $?;
+	commit $CHANGELOG "${REVISION_TYPE^^} $FULL_VERSION Update CHANGELOG.md" || exit $?;
 	
-	log "Success"
+	log "Changes successfully logged"
 }
 
 pushToChangelog;
